POST http://localhost:3000/api/wilder
Content-Type: application/json

{
    "name": "sammy"
}

###

GET http://localhost:3000/

###

GET http://localhost:3000/api/wilders

###

GET http://localhost:3000/api/wilders/3

###
PUT http://localhost:3000/api/wilders/2
Content-Type: application/json

{
    "name" : "jeannot"
}
###
DELETE http://localhost:3000/api/wilders/4

###

POST  http://localhost:3000/api/wilder/5/skill/4/add